apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redid-pod
    app: demo-voting-app
spec:
  containers:
    - name:  redis
      image: redis
      ports:
        - containerPort: 6379
